apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: dot-web
spec:
    build:
    environments:
        - name: prod
          build:
            from: PROD
        - name: test
          build:
            from: TEST   
        - name: dev
          build:
              from: main
    components:
        - name: frontend
          src: .
          publicPort: http
          ports:
              - name: http
                port: 3000