apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: prisma-decision-web

spec:
    build:
    environments:
        - name: prod
          build:
            from: PROD
        - name: test
          build:
            from: TEST   
        - name: dev
          build:
              from: main
    components:
        - name: frontend
          src: .
          publicPort: http
          ports:
              - name: http
                port: 3000
    dnsAlias:
        - alias: prisma
          environment: prod
          component: frontend
        - alias: prisma-test
          environment: test
          component: frontend
        - alias: prisma-dev
          environment: dev
          component: frontend 
        